services:
  mariadb:
    image: 'mariadb:11.4.2'
    environment:
      - 'MARIADB_DATABASE=dev'
      - 'MARIADB_PASSWORD=client'
      - 'MARIADB_ROOT_PASSWORD=root'
      - 'MARIADB_USER=myapp'
    ports:
      - '3306:3306'
