spring:
  application:
    name: micro-shop-app
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: 'jdbc:mariadb://localhost:3306/dev'
    username: 'myapp'
    password: 'client'
    hikari:
      allow-pool-suspension: true
      auto-commit: true
      connection-timeout: 100000
      idle-timeout: 3000000
      max-lifetime: 18000000
      maximum-pool-size: 100
      minimum-idle: 100
      pool-name: hikariPool
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
  jackson:
    datatype:
      enum:
        write-enums-to-lowercase: true
      json-node:
        read-null-properties: true
        write-null-properties: false
        write-properties-sorted: true
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    time-zone: UTC
    mapper:
      use-std-bean-naming: true
      accept-case-insensitive-enums: true
    serialization:
      write-dates-as-timestamps: true
      close-closeable: true
      write-enums-using-to-string: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  threads:
    virtual:
      enabled: true
server:
  port: 8090
  servlet:
    context-path: /api/v1
    application-display-name: MicroShopApp
    encoding:
      charset: UTF-8